version: "3.7"

services:
  server:
    env_file: "./server/.env"
    container_name: api
    build:
      context: ./server
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    restart: on-failure
    container_name: client
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

volumes:
  vol: