name: AWS-Deploy CD

on:
  push:
    branches: [main, ec2-deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the docker image
        run: docker-compose build

      - name: Generate Deployment Package
        run: zip -r deploy.zip *

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: scorecery
          environment_name: Scorecery-env
          region: eu-west-2
          deployment_package: deploy.zip

